version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Maps host port 8080 to container port 8080
    restart: always # Automatically restart the container if it crashes
